openapi: 3.0.0
info:
  title: Petro CRM
  description: Backend API documentation
  version: 0.1.0
servers:
  - url: http://localhost:8080
    description: Local Server
paths:
  /api/auth/signup:
    post:
      summary: Register a user.
      description: Creates a new user in a databse
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  required: true
                email:
                  type: string
                  required: true
                password:
                  type: string
                  required: true
                roles:
                  type: array
                  required: true
                  items:
                    type: string
      responses:
        '200': # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: User was registered successfully!
